- server/setup_server.sh
PM2 built-in solution looks really promising https://github.com/keymetrics/pm2-logrotate.
We did a few calculations on the size of the log files we want.
Each line of the Brave-Heartbeat-Server log file is ~144 bytes, we get 1 line per 10 seconds per installation, which for the viv means ~4MB of logs per day. 
We probably don't care about analyzing log periods longer than two weeks, which would be ~56mb.
We chose a log max size of 10mb, and are ok with default retention of 30 files because this gives enough breathing room in case we want to a larger period.
> added pm2 logrotate installation to setup_script

- chatbot/setup_server.sh
- server/ecosystem.config.js
- server/setup_server.sh
server processes weren't being restarted after certificate renewal due to a bug in the pre-renewal and post-renewal hooks. these commits fix that bug.
> fix bug in certificate renewal for chatbot & heartbeat servers

- README.md
- chatbot/.eslintrc.json
- chatbot/SessionState.js
- chatbot/SessionStateEnum.js
- chatbot/db/db.js
- chatbot/package-lock.json
- chatbot/package.json
- chatbot/server.js
- chatbot/test/SessionStateTest.js
- chatbot/test/serverTest.js
I added ESLint and enabled the recommended rules, as well as a rule for indentation (4 spaces per indent). The list of available rules is [here](https://eslint.org/docs/rules/) - in the future we'll enable more, for example regarding semicolons, but I stopped here for now.
Instructions for running the linter are in the readme. In the future we'll also add the linter to our testing infrastructure so that it runs automatically.
> Added ESLint for chatbot & made code compatible with recommended rules

- pairing-tool/.gitignore
- pairing-tool/index.js
- pairing-tool/package-lock.json
- pairing-tool/package.json
- pairing-tool/start_flicd.sh
This tool runs on a Raspberry Pi and uses the Flic Linux SDK. It provides an interactive command-line process for pairing buttons and associating unit numbers and phone numbers with the UUID of each button. It outputs a CSV file in the format that the add_installation.sh script uses. Overall this greatly streamlines the process of preparing for a new installation.
The tool is tested up to the point of generating the CSV file, and seems to work well. The CSV files that the tool creates haven't been tested with the add_installation.sh script yet.
> Made a tool to help pair large numbers of buttons

- chatbot/setup_server.sh
- heartbeat/setup_server.sh
Cron tasks execute with a minimal environment, meaning that the location of the pm2 executable was not on the PATH used by cron. This prevented the server process from restarting after certificate renewal took place.
I didn't catch this issue while testing the previous certificate renewal fix (#20) because I was copying the command from the crontab and executing it from a root shell, which had a different PATH setting. I tested this latest fix by changing the crontab to execute the command every minute instead of every week. In order to view the output of the cron jobs, I had to install a mail transfer agent (I used postfix, configured for local mail delivery only).
Relevant info:
https://askubuntu.com/questions/222512/cron-info-no-mta-installed-discarding-output-error-in-the-syslog …
> fixed an issue preventing server restart after certificate renewal

- CHANGELOG.md
A changelog following the structure described in https://keepachangelog.com/en/1.0.0/ 
I didn't go into any detail of the first versions (`1.0-pi-heartbeat` and `1.0-chatbot`). My thinking was that it's unlikely that anyone will need to look back that far and if I were to fill it in properly it would just be an exercise in describing an out-of-date system.
For the release dates, I just used the date of the commit with the tag on it. I'm pretty sure that this is often not the release date and/or the code was released on different devices on different days. Another option would be to just leave the dates off if I'm unsure about when they were actually released. I'm leaning towards showing this inaccurate dates because at least they give us some idea (hopefully nothing was released *before* …
> Add CHANGELOG.md (CU-5wd4g9)

- .travis.yml
- CHANGELOG.md
- README.md
- So that we can remove them from the Travis UI
- This will help us keep our environment variables in sync with the code
- More robust in case Travis somehow forgets our variables in the UI
- Easier to find, because the Travis UI doesn't make it super obvious
where they are or how to change them
- Updated README to include instructions (@schwarrrtz and @mariocimet , are you able to make the `travis encrypt --pro ...` command work for you locally?
> Add environment variables to Travis YAML (CU-b4m32r)

- CHANGELOG.md
- pi/heartbeat.py
- pi/sample_darkstat_html/log_ip.html
- pi/sample_darkstat_html/log_last_seen.html
- pi/test_heartbeat.py
- Seeing behaviour where Last Seen (Ping) is larger than Last Seen
(Flic), which doesn't make a lot of sense. So trying to see
exactly which IP address is being pinged, what the return code
from ping was, and which darkstat line provided the IP
- Also now log the FlicNotFoundError message from the object rather
than a generic message
- Added corresponding tests
I couldn't figure out how to test this on my local RPi because every time I plugged it in, I took down our local network. My guess is that because it was searching for the non-existent FlicHub every second, it was bogging down the system. Instead, I made mini python scripts to test just the functions that I changed locally to see that the logs turned out the way that I expected, and I added unit tests.
> Add logging to help debugging (CU-behg93)

- .travis.yml
- CHANGELOG.md
- chatbot/.env.example
- chatbot/server.js
- To ensure that these messages are not confusing for the fallback
staff, added the installation name to the message
- Unfortunately, the phone number that we are using in the tests for
the test rooms and for the test fallback from number need to be the
same because there is only one number that Twilio provides that will
succeed as a From number while using the test credentials. So I wasn't
able to write a test for this change
I pulled this change onto `chatbot-dev.brave.coop` and tested with my own phone as the responder and fallback phone. It worked as I expected.
> Use .env variable for fallback "from" phone number instead of the phone number of the room whose button press was unanswered (CU-6ed85y)

- CHANGELOG.md
- heartbeat/dashboard.mst
- heartbeat/server.js
- heartbeat/utils.py
Added a new endpoint called `POST unmute_system` that will unmute a muted system.
To help with testing this feature (and because I think it will be useful in real life), I also added a new "Muted?" column to the Heartbeat Dashboard that will display "Y" for systems that are muted and "N" for systems that are not muted.
While I was in there, I also noticed that there is a `POST hide_system` endpoint but no `POST show_system`. I'm wondering if this should be added as well. What do you think @schwarrrtz ?
> Add unmute API endpoint to Heartbeat (CU-baj2pv)

- heartbeat/dashboard.mst
- When first seeing the Heartbeat Dashboard, it is unclear what each of
the column is for. These explanations will hopefully help
- Also did a bit of HTML cleanup while I was here
Here's what it now looks like on `heartbeat-dev`:
> Add Last Seen definitions to dashboard (CU-bgjqh5)

- .travis.yml
- CHANGELOG.md
- chatbot/.env.example
- chatbot/db/db.js
- chatbot/helpers.js
- chatbot/server.js
- chatbot/test/serverTest.js
There's some documentation about how I investigated this in the clickup task, and test results for batch runs of tests. The only change here is to increase the amount of time that the test waits in between sending a test button press and checking the resulting session. This gives more time for the reminder and fallback message timers to expire, and for the several asynchronous calls that need to happen in between that and the message actually going out to conclude.
The timeouts add to 3000 milliseconds, so increasing from 3500 to 4000 doubles the extra time for those asynchronous calls.
> CU-byp1m3 + CU-3j6jj7 - Investigate Flakey Test

- CHANGELOG.md
- ops/setup_pi.yaml
I tested this while setting up the Minna Lee range test hub, and it seems to work well.
> ansible updates the comments in the remote access authorized_keys file

- CHANGELOG.md
- server/server.js
This also changes the fallback timeout to 4 minutes (so that it continues to be 2 minutes after the reminder message
> Change reminder timeout to 2 minutes (CU-eanm0j)

- CHANGELOG.md
- server/db/008-alternumpressestonumeric.sql
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/setup_postgresql.sh
- server/test/serverTest.js
It might be easiest to go through this PR by going through the commits rather than looking at all the code at once.
There are four main changes:
1. When there is a **double click**, Power Automate / Flow sends the parameter `Type=double click`. However, in the code, we were looking for `double_click` (with an underscore). This means that when we received a request with `Type=double click`, we were treating it the same as a single click. This means that we might have missed the initial message for some urgent requests (they would still have received the reminder and fallback messages).
2. When a request comes in to `POST /` from Power Automate / Flow, this now counts it as only 0.5 of a button press. This will hopefully band-aid over the problem where it always **sends us two copies of …
> A number of tweaks to make the button-press handling more consistent (CU-f0w9qm)

- CHANGELOG.md
- server/.gitignore
- server/chatbotDashboard.mst
- server/login.html
- Put list of installations into dropdown in nav bar
- Updated page to be responsive for ease of use on mobile/at smaller resolutions (mobile is zoomable but best in landscape)
- Removed unused nav bar from login.html, added some additional styling
- Added log out button to nav bar as route existed but had nothing directing to it
- Updated page titles to match dashboard nav (Brave Chatbot Dashboard), may want to change this if it will be called buttons in the future which I think is the case? But went with what the dashboard itself said for consistency
Note: changes are currently up on chatbot-dev if people are wanting to see them/ask for style revisions without much effort involved :)
> Display all installations on dashboard (CU-fmudrh)

- .travis.yml
- CHANGELOG.md
- server/.env.example
- server/server.js
- server/test/serverTest.js
- To be used to verify that all the Buttons are correctly configured
with the right API key before enforcing this authorization
> Add API key logging to `/flic_button_press` endpoint (CU-gwxnde)

- CHANGELOG.md
- server/package-lock.json
- server/package.json
- server/test/serverTest.js
- Add Twilio back as a dev dependency
- Mock Twilio's `validateExpressRequest` function to satisfy `brave-alert-lib`'s `handleTwilioRequest` in `serverTest.js`
> Validate Twilio requests (CU-dgmfbv)

- CHANGELOG.md
- server/package-lock.json
- server/package.json
- So that we get the latest Twilio, which has the latest axios, which
contains a high severity security fix
- In order for the twilio mocking to continue working in the integration
tests, I needed to re-generated package-lock.json, so this also
upgraded a bunch of other libraries
To test this change, I deployed this branch on chatbot-dev and did the following:
1. Used the /flic_button_press endpoint to "press" a button, respond "OK", respond "1", respond "Details"
2. Used the /flic_button_press endpoint 5 times, don't respond to any text messages until after receiving the fallback, then respond "OK"
3. Repeated 1 and 2 with the / endpoint
> Upgrade brave-alert-lib to v2.2.0 (CU-j6yuzk)

- CHANGELOG.md
- server/BraveAlerterConfigurator.js
- server/db/db.js
- server/server.js
- server/test/BraveAlerterConfiguratorTest.js
- server/test/dbTest.js
- server/test/testingHelpers.js
- Added try/catches to all the async functions. This should handle all our promise rejections.
- At the moment, the `catch` blocks generally don't do anything interesting. They just log the error. This follows what @mariocimet did in the BraveSensor-Server codebase. This would probably be a good place to introduce Sentry into our code. Then we can be notified when these happen in production.
- Added rollbacks in the `catch` blocks of functions that use DB transactions. This might help remove the deadlock problems that we've been seeing when running the tests.
I tried writing some automated tests for this, but as soon as I'd try to catch the promise rejection, then it would not longer be unhandled and hence the error would go away. So I just tried a few things out manually to see if the …
> Handle all promise rejections in async functions (CU-brqahw)

- .travis.yml
- CHANGELOG.md
- pairing-tool/setup_pi.sh
- server/setup_server.sh
This means that they will always use the exact versions specified in the package-lock.json file, thus ensuring more consistent builds (see NPM docs: https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable)
Note that the Task only specifies to do this for `/server`. I also made the change for the `/pi` directory. I think we had talked about this before and came to the conclusion to only do `/server`, but now I can't remember why. Do you remember @schwarrrtz or @mariocimet ?
I also added the missing deployment date from the CHANGELOG that I forgot.
> Use `npm ci` instead of `npm install` for Travis and deployment scripts (CU-jcwffp)

- CHANGELOG.md
- server/db/db.js
- server/ecosystem.config.js
- server/package-lock.json
- server/package.json
- This will add the timestamp to error output in production
> Use helpers.logError instead of console.error (CU-jcuw85)

- CHANGELOG.md
- README.md
- server/.env.example
- server/Installation.js
- server/db/011-alterfallbackphonenumbertobeanarray.sql
- server/db/012-renameregistrytobuttons.sql
- server/db/add_buttons_to_installation.sh
- server/db/add_installation.sh
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/setup_postgresql.sh
- server/setup_server.sh
- server/test/BraveAlerterConfiguratorTest.js
- server/test/serverTest.js
- Upgraded version of brave-alert-lib (https://github.com/bravetechnologycoop/brave-alert-lib/pull/10) takes an array of phone numbers for the fallbackPhoneNumbers parameter instead of just one.
- Changed `installations.fall_back_phone_number` column in the DB to be an text array, renamed it `fall_back_phone_numbers`, and migrated the current value in `fall_back_phone_number` into an array containing the old value.
- Updated tests accordingly
- Note that setup_server.sh 's script still only expects a single fallback number because at the point of running the migration file that needs that parameter, the column is still only expecting a text string containing a single phone number
- Tested this on chatbot dev:
- The fallback messages are sent to multiple phones
- Export CSV with an array …
> Add ability to send multiple fallback messages (CU-pv8hd5, CU-p107rc, CU-307j4h)

- CHANGELOG.md
- server/db/db.js
- This fixes a bug that only appears in our last release because we
now allow multiple sessions to be left in "Waiting for Reply".
This ensures that it will only get the most recent of those sessions.
> Always update the numPresses of the most recent unresponded session (CU-tb9pvc)

- CHANGELOG.md
- pi/heartbeat.py
- pi/test_heartbeat.py
- extra delay in run loop now depends on run loop duration
- the script now retries the heartbeat HTTP request once before turning off the Flic hub
> heartbeat.py - updates to run loop timing, added HTTP retry (CU-mrz5r1)

- CHANGELOG.md
- server/package-lock.json
- server/package.json
- To change `logSentry` to a message instead of an error
- To fix the route in handleTwilioMessage error messages
- ~~Didn't update the CHANGELOG because these two changes are modifications of things that already have an entry in the upcoming release's CHANGELOG.~~
Tested this by
- Deploying on `chatbot-dev`
- Replied to a Button-press alert with a phone that wasn't the Responder phone, and got the error message `21|BraveServer  | 2021-05-13 23:23:25.853: Bad request to /alert/sms: Invalid Phone Number`
- Manually changed the values in the `hubs` table to simulate a Hub reconnecting and disconnecting. This made a Sentry info message that looks like this: https://sentry.io/organizations/brave-technology-coop/issues/2397959388/?project=5743498&query=&statsPeriod=14d
> Update Brave Alert Lib

- CHANGELOG.md
- server/db/db.js
- server/server.js
- server/test/integration/serverTest.js
- No longer using it anywhere in production
- Removed the `presses` argument to `POST /flic_button_press` because it is also is not being used in production.
- Updated tests accordingly
THIS WILL BE A BREAKING CHANGE.
How I tested this:
- Tests pass on Travis
- Deployed to chatbot-dev
- Used Postman to hit `POST /flic_button_press` to simulate button presses in the following scenarios:
- Respond right away to the full chatbot
- Do not respond until after the reminder and the fallback have been sent
- Multiple presses to see urgent message at 2nd message and every 5th message
- Took a peek at Dashboard and Heartbeat dashboard and both look normal
- Used Postman to hit `POST /` and make sure that it returns a 404
- Used Postman to hit `POST /flic_button_press?presses=2` to make sure that it …
> Remove POST / endpoint (CU-fmunf5)

- CHANGELOG.md
- README.md
- server/setup_server.sh
- After upgrading to Ubuntu 20.04, the version of pm2 that we use
changed from 3.5.1 to 4.5.6
- For some reason, this meant that running the `setup_server.sh` as
it was and also the scheduled `pm2 restart` cron job failed to
properly restart the job. Instead, they would do weird things like
spawning a new server.js node process but not kill the old one, so
the server would still be running the old code. Other times, it
would leave the `pm2 status` view with no running code. Very strange
- These changes will run PM2 and the BraveServer node app as the brave
user instead of root. This means that when running pm2 commands
manually, we no longer need to use sudo. And when running pm2 command
in setup_server.sh, we need to specify to run them using the brave
user
My definition of "a working …
> Fix PM2 issues after Ubuntu 20.04 upgrade

- .vscode/launch.json
- CHANGELOG.md
- So that those of us who use VS Code will be able to use it to
debug Mocha tests without any extra work
Some screenshots of how it works from the equivalent change in BraveSensors: https://github.com/bravetechnologycoop/BraveSensor-Server/pull/114/files
> Add VSCode launch config for debugging Mocha tests for /server

- .travis.yml
- CHANGELOG.md
- server/.env.example
- server/BraveAlerterConfigurator.js
- server/SessionState.js
- server/chatbotDashboard.mst
- server/db/014-addrespondedattosessions.sql
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/setup_postgresql.sh
- server/test/integration/dbTest/getHistoricAlertsByAlertApiKeyTest.js
- server/test/integration/serverTest.js
- server/test/testingHelpers.js
- server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js
- server/test/unit/BraveAlerterConfiguratorTest/getHistoricAlertsByAlertApiKeyTest.js
- server/test/unit/dbTest.js
- To be used by the Alert App
- Added `responded_at` column to the `sessions` table because this
needs to be returned by the new endpoint
- Added functionality to set the `session.responded_at` column at
the appropriate times
- Added "Responded At" column to the Chatbot Dashboard
- Moved `SESSION_RESET_TIMEOUT` into the .env so that it would
be easily accessible from `BraveAlerterConfigurator.js` without
needing to pass it in to the constructor. This is also good for
manual testing because waiting 2 hours can suck. So it'll be good
to be able to just change the .env and redeploy to wait for a
shorter period of time to test this functionality
- Added and changed tests accordingly
- Changed all sinon.stub(helpers, 'log*') calls to use sinon.spy
instead so that I could still see the log …
> Add GET /alert/historicAlerts endpoint and `sessions.responded_at` column (CU-hjwfx2)

- .travis.yml
- CHANGELOG.md
- server/audit-ci.json
This pull request adds the same `audit-ci` tool to Travis as I added in this BraveAlert pull request: https://github.com/bravetechnologycoop/brave-alert-app/pull/11
> added audit-ci to Travis to check for security issues in server deps

- CHANGELOG.md
- README.md
- To add instructions to check the deployment ClickUp Tasks because we
occasionally forget things that we've noted or subtasked in there that
we should do (e.g. migrate the server)
- To add steps to message the team and the Responder phones whenever we
are about to start a deployment and whenever we finish a deployment,
so that everyone is aware that there will be downtime
I didn't test this :wink:
> Update deployment instructions (CU-wb8719)

- CHANGELOG.md
- server/db/db.js
- Postgres doesn't use the standard date/time format string that is
used in programming languages. Instead, "HH" means 12-hour hours
when what we wanted was "HH24" to get 24-hour hours and "MM" means
months when what we wanted was "MI" to get minutes
Test Plan:
- :heavy_check_mark:  Deploy to `chatbot-dev`, export the CSV, check all 5 date/time columns against the values in the DB and make sure that they are right even when the hour is > 12 and the minute is different than the month's number.
> Fix time formatting in CSV Export (CU-zkkach)

- CHANGELOG.md
- server/server.js
- server/test/integration/serverTest.js
- This makes it more difficult for people to hit our endpoint
pretending to be a Button when really they aren't.
- Gives us better security against this attack
- Also made the formatting and prettier-ignores more consistent in `serverTest.js`
- :heavy_check_mark: Check that there have been no `INVALID` logs in production in all the logs that we have right now (right now, this covers July 6-20)
- :heavy_check_mark: Deploy to chatbot-dev
- :heavy_check_mark: Configure my real buttons to hit `POST /flic_button_press` with the real API key
- :heavy_check_mark: Starts chatbot session
- :heavy_check_mark: Configure my real buttons to hit `POST /flic_button_press` with an invalid API key
- :heavy_check_mark: Doesn't starts chatbot session
- :heavy_check_mark: Logs the invalid API attempt
- …
> POST /flic_button_press returns 401 when given invalid API Key (CU-gwxnde)

- CHANGELOG.md
- server/BraveAlerterConfigurator.js
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumberTest.js
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js
- server/test/integration/dbTest/getHistoricAlertsByAlertApiKeyTest.js
- server/test/integration/serverTest.js
- server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js
- server/test/unit/BraveAlerterConfiguratorTest/getReturnMessageTest.js
- server/test/unit/SessionStateTest.js
- To upgrade `brave-alert-lib`
- :heavy_check_mark: Deploy to chatbot-dev.brave.coop
- :heavy_check_mark: Trigger both a Not-Urgent and Urgent Alert using my test Button
- :heavy_check_mark: Go through all chatbot states: Started, Waiting for Reply, Waiting for Incident Category, Waiting for Details, Completed
> Change `ALERT_STATE` to `CHATBOT_STATE`

- CHANGELOG.md
- server/.env.example
- server/BraveAlerterConfigurator.js
- server/Installation.js
- server/db/016-addresponderpushidtoinstallations.sql
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/setup_postgresql.sh
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumberTest.js
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionBySessionidAndAlertApiKeyTest.js
- server/test/integration/BraveAlerterConfiguratorTest/getNewNotificationsCountByAlertApiKeyTest.js
- server/test/integration/dbTest/getActiveAlertsByAlertApiKeyTest.js
- server/test/integration/dbTest/getHistoricAlertsByAlertApiKeyTest.js
- server/test/integration/serverTest.js
- server/test/unit/BraveAlerterConfiguratorTest/getActiveAlertsByAlertApiKeyTest.js
- server/test/unit/BraveAlerterConfiguratorTest/getHistoricAlertsByAlertApiKeyTest.js
- server/test/unit/BraveAlerterConfiguratorTest/getLocationByAlertApiKeyTest.js
- Updated brave-alert-lib to add the new endpoints for acknowledging an alert and setting an incident category and to change the behaviour of the designatedevice endpoint to also log the OneSignal Push ID.
- Use new `sendAlertSessionUpdate` function instead of `sendSingleAlert` when sending out Urgent Button Press Alerts. This will send the urgent messages using Push Notifications if it can
- Added a `db.clearTables` function that will delete everything in sessions, installations, notifications, and buttons tables in the right order so that we don't have to remember to do it properly in each integration test.
- ✔️  Passes the test plan in https://github.com/bravetechnologycoop/brave-alert-lib/pull/18
> Add OneSignal Push notifications (CU-10xfkhr)

- CHANGELOG.md
- server/BraveAlerterConfigurator.js
- server/db/db.js
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js
- server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js
This is just a one-liner, but I took the opportunity to do some clean up in the session-related functions in `db.js` since they will be tested in this test plan and are sort of related to what I changed.
- :heavy_check_mark: Deploy to `chatbot-dev`
- :heavy_check_mark: Use Postman to simulate a button press and see the respondedAt value is `null`
- :heavy_check_mark: Respond 'OK' and see the respondedAt value change to the current time on the Dashboard
- :heavy_check_mark: Respond to the incident category question with a valid incident category and see the respondedAt value does not change
- :heavy_check_mark: Respond to the incident category question with an invalid incident category and see the respondedAt value does not change
- :heavy_check_mark: Respond to the incident details …
> No longer update Responded At when given an invalid incident category (CU-1ae1j60)

- CHANGELOG.md
- pairing-tool/setup_pi.sh
- pi/setup_pi.sh
- Raspian OS version has changed from Buster to something else. So now,
Buster, the one that is on our devices, is considered `oldstable`
instead of `stable`. This fix came from:
https://forums.raspberrypi.com/viewtopic.php?t=318302
- :heavy_check_mark: Run `apt update --allow-releaseinfo-change` manually on the Kye7e hub just to make sure that it works with `apt update` (when we did this during the last deployment, we used `apt-get update`)
- :heavy_check_mark: Make these change to `setup_pi.sh` file on Alvis 1R Hub (which was missed during the previous deployment because it was offline at the time) and manually run `sudo ./BraveButtons/pi/setup_pi.sh ./BraveButtons/pi/pi_config.ini` to make sure that the changes to the script will work
- :heavy_check_mark: Run the Ansible script on just …
> Allow releaseinfo changes on RPis (CU-1kxmhta)

- CHANGELOG.md
- server/.env.example
- server/package-lock.json
- server/package.json
- :heavy_check_mark: Deploy to `chatbot-dev`
- On Android
- :heavy_check_mark: Custom sound used for push notifications when Alert is in the foreground
- :heavy_check_mark: Custom sound used for push notifications when Alert App is closed
- :heavy_check_mark: Custom sound used for push notifications when Alert App is in the background
- :question: Custom sound stops when the the app is opened (this seems to work when I use the notification to open it, but not when I open it through the normal app)
- On iOS
:heavy_check_mark: Custom sound used for push notifications when Alert is in the foreground
- :x: Custom sound used for push notifications when Alert App is closed
- :x: Custom sound used for push notifications when Alert App is in the background
- :question: Custom sound stops when the …
> Add custom sound to push notifications by updating brave-alert-lib (CU-10xfkhr)

- CHANGELOG.md
- ops/setup_pi.yaml
ansible doesn't support allowing releaseinfo changes; apt update still runs eventually because of the setup script.
> setup_pi.yaml no longer triggers apt update using the apt module

- CHANGELOG.md
- server/server.js
This came up while I was testing https://github.com/bravetechnologycoop/BraveSensor/pull/137 . I was able to use Postman with the logged in cookie from the browser to download the CSV Export even after I had logged out in the browser.
- If users had a copy of an cookie, they could still use it
to see the dashboard pages even after the user logs out
- Recommended to make cookies secure and httpOnly in
https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely
- :heavy_check_mark:  Deploy to `chatbot-dev`
- :heavy_check_mark:  Use Postman to try to download the CSV Export using the cookie from the browser
- :heavy_check_mark:  I'm able to download it when I'm logged in
- :heavy_check_mark:  I'm unable to download it when I'm logged out
>  Improve session and cookie security on dashboard

- CHANGELOG.md
- README.md
- ops/setup_pi.yaml
Some updates to the README and to `setup_pi.yaml` as we were going through the provisioning process for Norland Hub 2.
- :heavy_check_mark: Provision Norland Hub 2
> Changes during Norland Hub 2 provisioning (CU-vf96g1)

- server/db/db.js
- The `db.getHistoricAlertsByAlertApiKey` function compares
`maxTimeAgoInMillis` against the `updated_at` value in the DB. It's
possible that this test is running so fast that it has been less than
one millisecond since the `db.createSession` completed, in which case
we would get the wrong value back. So I changed the DB query to compare
<= instead of <. This will not make any real difference to the behaviour
in real life (because a 1ms difference doesn't really matter to humans)
but should make this test more reliable.
> Fix flaky getActiveAlertsByAlertApiKey integration test

- CHANGELOG.md
- pi/setup_pi.sh
this pull request changes `setup_pi.sh` so that the hostname can be repeatedly changed. the previous implementation would only work when changing the hostname from the default value of 'raspberrypi'.
thanks @trisapeace for the idea on how to implement this.
I tested this by manually running `setup_pi.sh` on a test hub while changing the hostname in `pi_config.ini`. each time the hostname was updated properly in both `/etc/hostname` and `/etc/hosts`. the hub was also able to connect to the internet and appeared normally on the heartbeat dashboard.
> setup_pi.sh sets the hostname in a more robust way (CU-40tzeq)

- CHANGELOG.md
- server/setup_server.sh
- :heavy_check_mark:  Run on `chatbot-dev` without any keyboard entry
- :heavy_check_mark: After running, on `chatbot-dev`, see that:
- :heavy_check_mark: Able to SSH from my normal IP
- :heavy_check_mark: Able to SSH from a new IP (used a phone hot spot)
- :heavy_check_mark: See port 22 open when running `sudo ufw status`
- :heavy_check_mark: On my local machine, delete my local database and run `setup_postgres.sql` without any parameters to see that it still works and that it puts a single dummy installation in the `installations` table
> Make the setup server script non-interactive (CU-brhk3t)

- CHANGELOG.md
- server/rak.js
- server/test/integration/rakTest/handleButtonPressTest.js
- This is to encourage putting the RAK Buttons into the Button
Covers in the correct orientation. Hopefully someone would notice
if they were put in incorrectly if the Button doesn't work
- :heavy_check_mark: Deploy to Buttons Dev
- :heavy_check_mark: Use postman to send a Button 1, 2, and 4 press to see that it doesn't send a text message
- :heavy_check_mark: Use postman to send a Button 3 press to see that it does send a text message
- :heavy_check_mark: Use postman to send two Button 3 presses to see that it sends the Urgent text message
- Use a real RAK button and press Button 1, 2, and 4 to see which light pattern shows up
> RAK Buttons 1, 2, and 4 no longer start the chatbot (CU-240e9z3)

- CHANGELOG.md
- README.md
We want to start using the new Twilio Studio Flows to send out these emails. It will be less error prone and will not give out our personal cell phone numbers to everyone with a Responder Phone.
- :heavy_check_mark: Ask Sampath if the instructions make sense
> README updated to use Twilio Flow to send deployment notifications (CU-2ajy0ec)

- CHANGELOG.md
- server/aws.js
- This seems to happen after 3 months of gateway inactivity. So we
need to cover this case
- It also means that we'll be able to add new rows to `gateways`
before we've the gateway connects to AWS for the first time, this
could be useful as we speed up Buttons provisioning
- :heavy_check_mark: Deploy to Dev
- :heavy_check_mark: When it checks the vitals of a gateway that has no Last Uplink At timestamp in AWS
- :heavy_check_mark: Does not log a row in `gateways_vitals`
- :heavy_check_mark: Does not log an error
- :heavy_check_mark: Does not send an error to Sentry
- :heavy_check_mark: When it checks the vitals of a gateway that does have a Last Uplink At  timestamp in AWS
- :heavy_check_mark: Logs a row in `gateways_vitals`
- :heavy_check_mark: Does not log an error
- :heavy_check_mark: …
> getGatewayStats will return `null` if there is LastUplinkReceivedAt (CU-2dm6j58)

- CHANGELOG.md
- server/dashboard.js
- server/db/034-addclientsextensiontable.sql
- server/db/db.js
- server/setup_postgresql.sh
- Used an extension table because this data is only every used by
the CSV export and I didn't want to have to alter the Client
object to add fields that aren't used anywhere else in the
program. This also gives the flexibility to easily add and remove
columns in this table for this need as more reporting requirements
come up or change
- For now, it is an MVP and is not included
on the New Client or Update Client pages. If it is missing when
someone does the CSV export and they need it filled in, they
can ask someone to add it to the DB
- Just used the `text` datatype to keep this super flexible for now.
If we find that it's a problem later, we can introduce an enum type.
- Every time a new client is added to the DB, automatically create an
empty row in the clients_extension table for it. …
> Add Country, Country Subdivision, and Building Type to CSV Export (CU-2c6crcn)

- CHANGELOG.md
- server/BraveAlerterConfigurator.js
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumbersTest.js
- When an SMS arrives from a phone, use both the fromNumber and the
toNumber to determine the most recent session instead of just the
toNumber. The toNumber should match one of the Buttons' phone number
and the fromNumber should match one of the clients'
responderPhoneNumbers. If there is one that works for both, then it's
the right session, if not, then it didn't find any
- Note that an SMS can come from any of the client's
responderPhoneNumbers, not just the one that initially responded to
the session
- :heavy_check_mark: Deploy to Dev
- Set up two clients as follows:
- Client 1:
- ResponderPhoneNumber: My phone number
- Button A:
- TwilioPhoneNumber: Valid dev Twilio number
- Client 2:
- ResponderPhoneNumber: James' phone number
- Button B:
- TwilioPhoneNumber: SAME valid dev Twilio …
> Allow Twilio numbers to be shared across clients (CU-2fk3y8a)

- CHANGELOG.md
- server/.env.example
- server/db/db.js
- server/server.js
- server/test/unit/vitalsTest/checkButtonBatteriesTest.js
- server/test/unit/vitalsTest/checkButtonHeartbeatTest.js
- server/vitals.js
- For now, only sends to Sentry so that we can restrict
it to just us Brave people until we know for sure that these messages
are reliable and not too noisy
- :heavy_check_mark: Run through normal chatbot
- :heavy_check_mark: Set my client and my Button to active
-  :heavy_check_mark: Sentry receives the Button disconnect message when buttonVitals.createdAt is older than the threshold
- :heavy_check_mark: Sentry receives the Button reconnection message when buttonVitals.createdAt is more recent than the threshold
- :heavy_check_mark: Set my client to active but Button to inactive
- :heavy_check_mark: Do not receive any Sentry messages
- :heavy_check_mark: Set my client and Button to inactive
- :heavy_check_mark: Do not receive any Sentry messages
- :heavy_check_mark: Set my client to …
> Send disconnection messages to Sentry for RAK Buttons (CU-208arfp)

- CHANGELOG.md
- server/rak.js
- server/test/integration/rakTest/handleButtonPressTest.js
- The new injection-moulded Buttons will push on Button 4 instead of Button 3. We still have 3D-printed Buttons in production, so did not remove the alerting ability of Button 3, which it uses.
- ✔️ Deploy to Dev
- ✔️ Push Button 4 once and multiple times, should start an alert and also send expected urgent alerts
- ✔️ Push Button 3 once and multiple times, should start an alert and also send expected urgent alerts
- ✔️ Push Button 1 once and multiple times, should NOT start any alerts
- ✔️ Push Button 2 once and multiple times, should NOT start any alerts
- ✔️ Push a combination of Buttons 3 and 4, should start an alert and also send expected urgent alerts
> Pressing RAK Button 4 starts an alert (CU-2uadjfh)

- CHANGELOG.md
- server/i18nextHelpers.js
- server/resources/translations/common.es_us.json
- server/test/unit/BraveAlerterConfiguratorTest/getReturnMessageToRespondedByPhoneNumberTest.js
- :heavy_check_mark: Deploy to dev
- :heavy_check_mark: Set my physical RAK Button system up to use Spanish
- :heavy_check_mark: Go through the chatbot and see that each one of the strings is sent to me as expected with the right values filled in:
- :heavy_check_mark:  "alertAcknowledged": "Otro personal de auxilio ha confirmado esta solicitud. (No necesita responder a este mensaje).",
- :heavy_check_mark: "alertCompleted": "Gracias. Esta sesión ya está completa. (No necesita responder a este mensaje).",
- :heavy_check_mark: "alertFallback": "Ha habido una solicitud sin respuesta en {{ clientDisplayName }} {{ buttonDisplayName }}",
- :heavy_check_mark: "alertReminder": "Responda \"Ok\" si le ha dado seguimiento a su llamada. Si no responde dentro 2 minutos, se emitirá una alerta de …
> Add US Spanish translations for chatbot (CU-38tu7z8)

- CHANGELOG.md
- server/package-lock.json
- server/package.json
- There were some deprecations in the API that I hope are updated in the libraries
- :heavy_check_mark: Deploy to dev
- :heavy_check_mark: LastUplink timestamp can be retrieved from AWS and displayed on the Vitals page for RAK Gateways
- :heavy_check_mark: Register a Button in PA
> Update AWS IoT libraries (CU-3c6mw16)

- CHANGELOG.md
- server/ButtonsVital.js
- server/dashboard.js
- server/db/038-addbuttonsvitals-snrrssi.sql
- server/db/db.js
- server/mustache-templates/clientVitals.mst
- server/mustache-templates/vitals.mst
- server/rak.js
- server/setup_postgresql.sh
- server/test/integration/dbTest/getActiveAlertsByAlertApiKeyTest.js
- server/test/integration/rakTest/handleButtonPressTest.js
- server/test/testingHelpers.js
It'll be useful for us to record as we move to larger buildings that aren't local to us to see how strong the signal is between a button and its hub.
- It automatically rounded `13.3333333333333333333333333333333333` to `13.333333333333334`. This seems OK to me.
- It automatically rounded `13.3333333333333333333333333333333333` to `13.333333333333334`. This seems OK to me.
> Add RSSI and SNR to the Buttons Vitals table and stop logging it (CU-2a7dcrz)

- .travis.yml
- CHANGELOG.md
- server/api.js
- server/db/db.js
- server/routes.js
- server/server.js
- server/test/integration/apiTest/messageClientsTest.js
- server/test/unit/apiTest/authorizeTest.js
The API call /api/message-clients sends text messages to active clients.
It works as follows:
For all clients that are sending vitals, sending alerts, and have at least one button that is sending vitals and sending alerts, send a Twilio message containing the message that was POSTed to /api/message-clients.
Requires proper submission of the Particle Accelerator API key (braveKey); this is because the API call is intended to be called from PA.
Upon successful submission of the API key, the server will respond with a JSON object containing information about contacted/failed clients:
```json
{
"status": "success",
"message": "This is the text message that was sent!",
"contacted": [
{
"to": "+11111111111",
"from": "+12222222222",
"clientId": "01234567-89ab-cdef-0123-456789abcdef", …
```
> POST /api/message-clients (CU-w9bcb5)

- CHANGELOG.md
- server/.env.example
- server/pa.js
- server/package-lock.json
- server/package.json
- server/routes.js
This PR updates the PA API routes `/pa/aws-device-registration` and `/pa/buttons-twilio-number` to use `googleHelpers.paAuthorize` instead of `clickUpHelpers.clickUpChecker`.
It also upgrades `brave-alert-lib` to v10.3.1, which removes the `clickUpHelpers` export, with `googleHelpers` being its replacement.
Test plan:
> Updated PA API routes to use googleHelpers (CU-8679128d6)

- CHANGELOG.md
- server/db/db.js
- server/pa.js
- server/routes.js
- server/test/unit/paTest/handleCheckDatabaseConnectionTest.js
This PR is part of the broader Clickup task to create a system status page in PA. These changes include creating a route to check if the BraveButtons database connection is working as expected (by running one simple db query). PA will hit this route with a `googleIdToken` and `braveKey`. Upon getting the response, PA will  display a green icon if the connection is working or a red icon if it is not. 
- Unit Test for `pa.handleCheckDatabaseConnection`
- Other Testing
> Add Route to Check the Database Connection (CU-86dqkw7ef)

- CHANGELOG.md
- server/db/040-deprecate-one-signal.sql
- server/db/db.js
- server/package-lock.json
- server/package.json
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumbersTest.js
- server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js
- server/test/integration/serverTest.js
This PR removes the alert API key and responder push ID fields from clients. I.e., the respective columns in the database, as well as all factory calls to create or updates clients, are updated.
Test Plan:
> Deprecate OneSignal as used in Clients (Alert API Key, Responder Push ID) (CU-86dqkmhza)

- CHANGELOG.md
- server/BraveAlerterConfigurator.js
- server/package-lock.json
- server/package.json
This PR disables and rejects the reset chatbot flow. To do this, it has the `getClientMessageForResetMessage` argument to `BraveAlerter` return `null`, which disables the alert state machine transition from `STARTED` or `WAITING_FOR_REPLY` to `RESET`. The result is no change to the existing Buttons chatbot.
- BraveAlerterConfigurator to reject the RESET state (CU-860r8k57h).
> Disable and reject the reset chatbot flow if it occurs (CU-860r8k57h).
