.travis.yml
This was part of your README doc on how to run the tests, but I didn't get around to adding it to Travis until now. So here it is.
=> Add test coverage to Travis

chatbot/SessionState.js, chatbot/db/004-addalertflag.sql, chatbot/db/db.js, chatbot/server.js, chatbot/setup_postgresql.sh, chatbot/test/serverTest.js
See issue #8 for discussion that led to this
=> Testing that a fallback alert is actually sent

chatbot/setup_server.sh, heartbeat/setup_server.sh
- replaced cron cert renewal with simple weekly restart; certbot install handles renewal
- tweaked setup script behaviour to restart a running server process or start a new one
=> setup script updates

CHANGELOG.md, server/chatbotDashboard.mst, server/server.js
Add landing page which either informs user that no installations are available, or asks them to select one to view
=> Add dashboard landing page (CU-gurbtf)

README.md
noticed this while doing manual testing yesterday - flic_button_request in the URL is a 404 Error
=> Fixed Internet Request pairing instructions

CHANGELOG.md, server/SessionState.js, server/chatbotDashboard.mst, server/db/010-addbatteryleveltosessions.sql, server/db/db.js, server/server.js, server/setup_postgresql.sh, server/test/BraveAlerterConfiguratorTest.js, server/test/serverTest.js
Tested on chatbot-dev, I've saved an extract of the registry column.
=> CU-fgyh0g adding battery level to sessions table and to dashboard 

server/.env.example
- To make it clearer what values need to be in order for tests to pass
=> Add comments to the .env.example file

.travis.yml, README.md, server/setup_postgresql_local_dev.sh
- Need to have the environment variables in sudo in order for the setup_postgresql_local.sh script to run correctly
This works for me on Ubuntu
@risatronic , you have a Mac right? Care you give it a shot there
@schwarrrtz , you're using Windows, right? Let's try them all!
=> Update local DB setup instructions in README (CU-g0tpd6)

CHANGELOG.md, server/.env.example, server/BraveAlerterConfigurator.js, server/db/db.js, server/package-lock.json, server/server.js, server/test/integration/serverTest.js, server/test/unit/dbTest.js
Up on chatbot-dev.brave.coop, you can track errors here:https://sentry.io/organizations/brave-technology-coop/issues/?project=5743498
one way to see it in action is to just `curl --data "bla=1" https://chatbot-dev.brave.coop/`
=> Added Sentry for aggregating and tracking errors and outages (CU-32a5wb)

CHANGELOG.md, server/BraveAlerterConfigurator.js, server/db/015-addnotifications.sql, server/db/db.js, server/package-lock.json, server/package.json, server/setup_postgresql.sh, server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumberTest.js, server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js, server/test/integration/BraveAlerterConfiguratorTest/getNewNotificationsCountByAlertApiKeyTest.js, server/test/integration/dbTest/getHistoricAlertsByAlertApiKeyTest.js, server/test/integration/serverTest.js
- the Alert App uses this to display the number of new notifications
- also added the notifications table to the db
- also updated and added tests
=> add GET /alert/newNotificationsCount endpoint (CU-hjwcwk)

CHANGELOG.md, server/BraveAlerterConfigurator.js, server/db/db.js, server/package-lock.json, server/package.json, server/test/integration/dbTest/getActiveAlertsByAlertApiKeyTest.js, server/test/unit/BraveAlerterConfiguratorTest/getActiveAlertsByAlertApiKeyTest.js, server/test/unit/BraveAlerterConfiguratorTest/getHistoricAlertsByAlertApiKeyTest.js
- Just needed a way to retrieve the ActiveAlerts from the DB and give them to brave-alert-lib.
- :heavy_check_mark: Passes all the tests in https://github.com/bravetechnologycoop/brave-alert-lib/pull/27
=> API changes for Push Notifications (CU-10xfkhr)

server/audit-ci.json, server/package-lock.json, server/package.json
Also updated the audit-ci.json to ignore a disputed critical security issue:
- Description of the issue: lodash/lodash#5261
- Description of why it's disputed by lodash: https://nvd.nist.gov/vuln/detail/CVE-2021-41720
- :heavy_check_mark: Complete all the tests in https://github.com/bravetechnologycoop/brave-alert-lib/pull/29
=> Update brave-alert-lib to send consistent JSON values in the API responses

CHANGELOG.md, server/db/db.js, server/server.js, server/utils.py
- These endpoints were insecure and most of us just change these values directly
in the database. One day, they will be changeable through the
Dashboard UI and that will be the safest way
- Love a pull request that does nothing but remove code, eh?
=> Remove hub modification endpoints (rename, mute, hide) (CU-dgm1bj)

CHANGELOG.md, README.md
=> updated hub programming instructions in README (CU-vf96g1)

CHANGELOG.md, pi/heartbeat.py, pi/test_files/sample_darkstat_html/90206_secs.html, pi/test_files/sample_darkstat_html/null_ips.html, pi/test_heartbeat.py
@schwarrrtz What sort of testing should I do on this?
=> Update darkstat parsing (CU-1k0zhbg)

CHANGELOG.md, README.md, pi/heartbeat.py
- added descriptions of the config repo and the pi template files to the README
- added additional comments to `heartbeat.py`
- added instructions for using the `--limit` flag with `ansible-playbook`
=> various documentation updates (CU-vf8v9x, CU-vf96g1)

README.md
Changes to made while provisioning the Norland Hubs to make things clearer for me next time I need to do this.
=> Update Ansible instructions in README

CHANGELOG.md, README.md, pairing-tool/.env.example, pairing-tool/.gitignore, pairing-tool/index.js, pairing-tool/package-lock.json, pairing-tool/package.json
- The pairing tool now optionally allows you to choose to buy an American or Canadian phone number by specifying the desired 3-digit area code. If you don't give a 3 character string for that option, it will assume that it is an existing phone number and just add it directly to the CSV following the previous functionality
- Also added more instructions on how to pair buttons and consolidated the pairing tool sections with it to hopefully make it clearer what to do
- :heavy_check_mark: Use this to pair all the new Norland buttons
- :heavy_check_mark: If given an area code (604)
- :heavy_check_mark: it buys the number
- :heavy_check_mark: uses "<client name> <unit>" as its friendly name
- :heavy_check_mark: adds the "All Buttons Messages" messaging service
- :heavy_check_mark: button with …
=> Buy twilio numbers in the Pairing Tool (CU-1tdma20)

README.md
- Changed `pm2 stop BraveServer` to `pm2 kill` to handle problem that
I ran into where environment variables were cached and didn't update
by a simple re-deploy
While I was in there, I made these other changes that will help me during production deployments:
- Moved production deployment instructions to top of README so that it's easier to find given that it's the part of the README that we use the most often
- Moved section of how to deploy to the Raspberry Pi fleet using
Ansible directly into the production deployment instructions to
eliminate the need to jump around the document during deployment
- Changed the big Ansible command to deploy the whole fleet to use
the `inventory-prod.yaml` instead of a placeholder to put either
the production or dev inventory. This will reduce issues …
=> Changed `pm2 stop BraveServer` to `pm2 kill` in deployment instructions

.gitignore, .vscode/settings.json, CHANGELOG.md, README.md, lambda/setup_lambda.sh, lambda/src/lambda_function.py
- Including instructions on how to generate the .zip file
and deploy it to AWS
- Sampath can update the lambda function and deploy it to dev and prod
=> Add AWS RAK LoRa lambda function (CU-1yuq5ju)

CHANGELOG.md, server/.env.example, server/audit-ci.json, server/aws.js, server/pa.js, server/package-lock.json, server/package.json, server/routes.js, server/server.js
Added two endpoints
- Buy a Twilio number for Buttons
- Register a RAK Button on AWS
- :heavy_check_mark: Deploy to Dev
- :heavy_check_mark: Use PA to buy a Dev Twilio number
- :heavy_check_mark: With valid area code
- :heavy_check_mark: Has correct messaging service
- :heavy_check_mark: Has a number in the right area code
- :heavy_check_mark: Has correct webhook URL
- :heavy_check_mark: Has the correct name
- :heavy_check_mark: With invalid area code
- :heavy_check_mark: Decent error message (it's not the best. It logs a good one, but puts something generic in the API response)
- :heavy_check_mark: With area code with no available numbers
- :heavy_check_mark: Decent error message (it's not the best. It logs a good one, but puts something generic in the API response)
- :heavy_check_mark: …
=> Add /pa endpoints for PA (CU-21ghk0x)

CHANGELOG.md, server/package-lock.json, server/package.json
- To get better error messages when purchasing a Twilio Number
- :heavy_check_mark: Automated tests pass
=> Update Brave Alert Lib

CHANGELOG.md, README.md
- To handle the new AWS SSO access to the buttons-config repo
=> Updated deployment instructions in README

ops/rak_button_firmware.ahk
Updated the documentation here: 
https://app.clickup.com/2434616/v/dc/2a9hr-2261/2a9hr-6207
=> Added buttons provisioning autohotkey script

CHANGELOG.md, server/audit-ci.json, server/package-lock.json, server/package.json
- This means that we could remove the audit-ci exception
=> Upgrade Brave Alert Lib and Twilio libraries (CU-860phzbq5)

CHANGELOG.md, server/setup_postgresql.sh
I have enhanced the Buttons DB migration process by introducing dynamic execution of SQL Migration Files, eliminating the need to maintain an explicit list.
test included:
=> Add update/improve db migration process (CU-8678vk9cj)

CHANGELOG.md, server/package-lock.json, server/package.json
- To fix a high severity security issue: https://github.com/advisories/GHSA-4q6p-r6v2-jvc5
=> Upgrade Chai and brave-alert-lib (CU-8678wgn0p)

.travis.yml, CHANGELOG.md, server/.env.example, server/db/db.js, server/server.js, server/setup_postgresql.sh, server/setup_postgresql_local_dev.sh
=> Create and use PG_DATABASE env var

server/dashboard.js, server/db/db.js, server/pa.js, server/rak.js, server/setup_postgresql.sh, server/test/integration/dbTest/getActiveButtonsClientsTest.js, server/test/unit/paTest/handleMessageClientsTest.js
=> Small fixes before database merge

CHANGELOG.md, server/rak.js, server/test/integration/rakTest/handleButtonPressTest.js, server/test/unit/buttonAlertsTest/handleValidRequestTest.js
Configured BraveButtons for RAK7201v2
Test Plan:
=> Ew new button config (CU-86dte4ejq)

CHANGELOG.md, server/db/042-rename-buttons-to-devices.sql, server/db/044-fixtriggerfunction.sql
Added migration script 44 to fix the function
Test Plan
=> Trigger function for vitals fix (CU-86dtk5h8k)

CHANGELOG.md, server/package-lock.json
=> Updating Braces Package (CU-86dtu06ga)

server/buttonAlerts.js, server/db/db.js
Fix database function to ensure that vitals are not sent for buttons with offline gateways
=> Disable vitals offline gateway (CU-86dtkwpn9)

CHANGELOG.md, README.md
Dev deployment added to the README
=> Added dev deployment to the README (CU-86dqu45n1)

CHANGELOG.md, server/mustache-templates/clientVitals.mst, server/mustache-templates/vitals.mst
=> Button to show/hide SNR and RSSI values in the dashboard (CU-86du4cpm8)

CHANGELOG.md, server/db/049-updateclienttables.sql
Here are the updates needed to the DB,
Country - clients_extension.country (existing)
Country subdivision - clients_extension.country_subdivision (existing)
Building type - clients_extension.building_type (existing)
Funder - clients_extension.funder (NEW)
Project - clients_extension.project (NEW)
Parent org - clients_extension.organization; (NEW)
Client name - clients.display_name (existing)
City - clients_extension.city (NEW)
Zip Code/Postal Code - clients_extension.postal_code (NEW)
organization, funder, postal_code has been added by Elana, seen in script 47
added script 49, to add the remaining fields.
=> Cc updateclienttables CU-86du6jp33

CHANGELOG.md, README.md, server/.env.example
Updated .env.example and README file for Buttons
- Removed outdated items in env.example and added new ones
- Changed README for how to notify active client during system downtime/uptime.
=> Updated .env.example and README file for Buttons (CU-86duebt59)

CHANGELOG.md, server/db/050-alter-deviceType-enum.sql, server/db/add_buttons_to_client.sh, server/db/add_client.sh, server/db/db.js, server/package-lock.json, server/package.json
- Updated **brave-alert-lib to v15.0.4** for deviceType enum change
- Added migration script (migrationID 50) to update device_type_enum to handle multi-stall and single-stall sensors separately.
- Updated device_type_enum to have 'DEVICE_BUTTON' to 'BUTTON'.
=> Update button device type in database (CU-86duvwbq2)

server/package-lock.json
=> updated cross-spawn

CHANGELOG.md, server/dashboard.js, server/db/db.js, server/mustache-templates/updateClient.mst
Fixed error caused due to updating client's first_device_live_at in dashboard
=> Fix update client dashboard page for Buttons (CU-86dvqgum0)
